export const LOGIN = 'LOGIN';
export const LOGGED_IN = 'LOGGED_IN';
export const LOGOUT = 'LOGOUT';
export const FETCH_WORKOUTS = 'FETCH_WORKOUTS';
export const FETCHED_WORKOUTS = 'FETCHED_WORKOUTS';
export const FETCH_NEW_WORKOUT = 'FETCH_NEW_WORKOUT';
export const FETCHED_NEW_WORKOUT = 'FETCHED_NEW_WORKOUT';
